spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    password: root
    username: root

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
